version: '2.1'

services:
  bear:
    image: bear
    user: "node"
    working_dir: /usr/src/bear
    build: .
    environment:
      NODE_ENV: production
    ports:
      - 8001:4001
    volumes:
      - ./:/usr/src/bear
    expose:
      - "4001"
    command: "npm start"
    depends_on: 
      - db
  
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on: 
      - db