version: '2.1'

services:
  bear:
    image: bear
    build: .
    environment:
      DEBUG: 'true'
      NODE_ENV: 'development'
    ports:
      - 3000:3000
      - 9229:9229
    ## set your startup file here
    command: node --inspect index.js